# Generated by Django 5.2.7 on 2025-10-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('interests', models.TextField()),
                ('goals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('what_i_learned', models.TextField()),
                ('reflection', models.TextField()),
            ],
        ),
    ]
